envVarGroups:
  - name: livekit-agent-secrets
    envVars:
      - key: LIVEKIT_URL
        sync: false
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false

services:
  - type: worker
    name: candidate-agent
    runtime: docker
    plan: starter
    region: singapore
    branch: Ahmed
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: uv run src/dynamic-agent.py start
    envVars:
      - fromGroup: livekit-agent-secrets
      - key: AGENT_NAME
        value: my-agent
